routes/web.php
<?php

use App\Http\Controllers\SaleController;

Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['auth']], function () {
	Route::get('/', 'Backend\BackendController@index')->name('home');	
});
		
Route::prefix('admin')->group(function () {
	Route::group(['middleware' => ['auth', 'role:admin']], function () {
		Route::resource('user', 'UserController');
	});
	
});

Route::resource('customer', 'CustomerController', ['names' => 'customer']);

Route::resource('product_category', 'ProductCategoryController', ['names' => 'product_category']);

Route::resource('product', 'ProductController', ['names' => 'product']);

Route::resource('sale', 'SaleController', ['names' => 'sale']);

Route::post('ajax/sub_category', 'AjaxController@sub_category')->name('ajax.sub_category');
Route::post('ajax/product_price', 'AjaxController@product_price')->name('ajax.product_price');
Route::post('ajax/customer_by_location', 'AjaxController@customer_by_location')->name('ajax.customer_by_location');


Route::get('customer_by_location', 'CustomerLocationcontroller@index')->name('customer_by_location.index');

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use DB;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{
	public function index()
	{
		// $role = Role::create(['name' => 'customer']);
		// $user = Auth::user();
		// $user->assignRole('admin');
		return view('backend.index');
	}

	
}

resources/views/backend/partials/footer.blade.php
<footer class="main-footer">
	<!-- Default to the left -->
	<strong>Copyright &copy; 2014-2019 <a href="https://www.ultrabyteit.com/" target="0">Utrabyte</a>.</strong> All rights reserved.
</footer>

resources/views/backend/partials/header.blade.php
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="csrf-token" content="{{ csrf_token() }}">


<title>
    Sales Recording System | @yield('title')
</title>

{{-- adminlte css --}}
<link rel="stylesheet" href="{{asset('adminlte/css/adminlte.min.css')}}">


<link rel="stylesheet" type="text/css" href="{{asset('adminlte/css/custom.css')}}">

<link rel="stylesheet" href="{{ asset('frontend/fontawesome-new/css/all.css') }}">

<link rel="stylesheet" href="{{asset('adminlte/css/bootstrap.min.css')}}">
{{-- <link rel="stylesheet" href="{{asset('bootstrap-4.5.0-dist/css/bootstrap.min.css')}}"> --}}

{{-- data table --}}
<link href="{{ asset('dataTable/css/jquery.dataTables.min.css') }}" rel="stylesheet">

{{-- select 2 --}}
<link href="{{ asset('select2/dist/css/select2.min.css') }}" rel="stylesheet" />

resources/views/backend/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">

  <!-- Left navbar links -->

  <ul class="navbar-nav">

    <li class="nav-item">

      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>

    </li>

    {{-- <li class="nav-item d-none d-sm-inline-block">

      <a href="#" class="nav-link">Home</a>

    </li> --}}

  </ul>

  <!-- Right navbar links -->

  <ul class="navbar-nav ml-auto">

    <!-- Notifications Dropdown Menu -->

    {{-- <li class="nav-item dropdown">

      <a class="nav-link" data-toggle="dropdown" href="#">

        <i class="fa fa-bell"></i>

        <span class="badge badge-warning navbar-badge">15</span>

      </a>

      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">

        <span class="dropdown-header">15 Notifications</span>

        <div class="dropdown-divider"></div>

        <a href="#" class="dropdown-item">

          <i class="fa fa-file mr-2"></i> 3 new reports

          <span class="float-right text-muted text-sm">2 days</span>

        </a>

        <div class="dropdown-divider"></div>

        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>

      </div>

    </li> --}}
    <ul class="navbar-nav pull-right">

    <li class="nav-item">

      <a class="nav-link" href="{{url('logout')}}"><i class="fa fa-sign-out"></i>Logout</a>

    </li>

  </ul>

  </ul>

</nav>

resources/views/backend/partials/script.blade.php
<!-- jQuery -->
<script src="{{asset('adminlte/js/jquery.min.js')}}"></script>
{{-- <script src="{{asset('jquery.min.js')}}"></script> --}}

<!-- Bootstrap 4 -->
<script src="{{asset('adminlte/js/bootstrap.min.js')}}"></script>
{{-- <script src="{{asset('bootstrap-4.5.0-dist/js/bootstrap.min.js')}}"></script> --}}

<!-- AdminLTE App -->
<script src="{{asset('adminlte/js/adminlte.min.js')}}"></script>

{{-- font awesome --}}
<script src="{{asset('adminlte/js/fontawesome.js')}}"></script>

{{-- jquery slim --}}
{{-- <script type="text/javascript" src="{{asset('adminlte/js/jquery_slim.min.js')}}"></script> --}}

{{-- popper js --}}
<script type="text/javascript" src="{{asset('adminlte/js/popper.min.js')}}"></script>


{{--ckeditor--}}
<script type="text/javascript" src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>

{{-- data table --}}
<script src="{{ asset('jQuery/jquery-3.3.1.js') }}"></script>
<script src="{{ asset('dataTable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('dataTable/js/dataTables.bootstrap4.min.js') }}"></script>

{{-- select2 --}}
<script src="{{ asset('select2/dist/js/select2.min.js') }}"></script>

resources/views/backend/partials/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">

  <!-- Brand Logo -->

  <a href="{{ route('home') }}" class="brand-link" target="1" <span
    class="brand-text font-weight-light">Sales Recording System</span>

  </a>



  <!-- Sidebar -->

  <div class="sidebar">

    <!-- Sidebar Menu -->

    <nav class="mt-2">

      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-header">
          {{ ucfirst(Auth::user()->name) }}
        </li>
        
        <li class="nav-header">Menu</li>
        
        
        <li class="nav-item has-treeview ">
          <a href="{{ route('home') }}" class="nav-link {{ (request()->routeIs('home')) ? 'active' : '' }}">

            <i class="fas fa-tachometer-alt"></i>

            <p>

              Dashboard

            </p>

          </a>
        </li>        
        
        
        <li class="nav-item has-treeview {{ (request()->routeIs('customer.*')) ? 'menu-open' : '' }}">

          <a href="#" class="nav-link {{ (request()->routeIs('customer.*')) ? 'active' : '' }}">

            <i class="fas fa-users"></i>

            <p>

              Customer

            </p>
            <i class="fas fa-angle-left right"></i>

          </a>

          <ul class="nav nav-treeview">

            <li class="nav-item ">

              <a href="{{ route('customer.create') }}" class="nav-link {{ (request()->routeIs('customer.create')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Add New Customer</p>

              </a>

            </li>

            <li class="nav-item">

              <a href="{{ route('customer.index') }}" class="nav-link {{ (request()->routeIs('customer.index')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Manage Customer</p>

              </a>

            </li>

          </ul>

        </li>        
        
        <li class="nav-item has-treeview {{ (request()->routeIs('product_category.*')) ? 'menu-open' : '' }}">
          
          <a href="#" class="nav-link {{ (request()->routeIs('product_category.*')) ? 'active' : '' }}">

            <i class="fas fa-puzzle-piece"></i>

            <p>

              Product Category

            </p>
            <i class="fas fa-angle-left right"></i>

          </a>

          <ul class="nav nav-treeview">

            <li class="nav-item">

              <a href="{{ route('product_category.create') }}" class="nav-link {{ (request()->routeIs('product_category.create')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Add New Category</p>

              </a>

            </li>

            <li class="nav-item">

              <a href="{{ route('product_category.index') }}" class="nav-link {{ (request()->routeIs('product_category.index')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Manage Category</p>

              </a>

            </li>

          </ul>

        </li>

        <li class="nav-item has-treeview {{ (request()->routeIs('product.*')) ? 'menu-open' : '' }}">

          <a href="#" class="nav-link {{ (request()->routeIs('product.*')) ? 'active' : '' }}">

            <i class="fas fa-box-open"></i>

            <p>

              Products

            </p>
            <i class="fas fa-angle-left right"></i>

          </a>

          <ul class="nav nav-treeview">

            <li class="nav-item">

              <a href="{{ route('product.create') }}" class="nav-link {{ (request()->routeIs('product.create')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Add New Product</p>

              </a>

            </li>

            <li class="nav-item">

              <a href="{{ route('product.index') }}" class="nav-link {{ (request()->routeIs('product.index')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Manage Product</p>

              </a>

            </li>

          </ul>

        </li> 
        
        <li class="nav-item has-treeview {{ (request()->routeIs('sale.*')) ? 'menu-open' : '' }}">

          <a href="#" class="nav-link  {{ (request()->routeIs('sale.*')) ? 'active' : '' }}">

            <i class="fas fa-coins"></i>

            <p>

              Sales

            </p>
            <i class="fas fa-angle-left right"></i>

          </a>

          <ul class="nav nav-treeview">

            <li class="nav-item">

              <a href="{{ route('sale.create') }}" class="nav-link {{ (request()->routeIs('sale.create')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Add New Sales</p>

              </a>

            </li>

            <li class="nav-item">

              <a href="{{ route('sale.index') }}" class="nav-link {{ (request()->routeIs('sale.index')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Manage Sales</p>

              </a>

            </li>

          </ul>

        </li> 

        @role('admin')
        <li class="nav-item has-treeview">
          <a href="{{ route('customer_by_location.index') }}" class="nav-link {{ (request()->routeIs('customer_by_location.index')) ? 'active' : '' }}">

            <i class="fas fa-map-marker-alt"></i>

            <p>

              Customer By Location

            </p>

          </a>
        </li>

        <li class="nav-item has-treeview {{ (request()->routeIs('user.*')) ? 'menu-open' : '' }}">

          <a href="#" class="nav-link {{ (request()->routeIs('user.*')) ? 'active' : '' }}">

            <i class="fas fa-user-tie"></i>

            <p>

              User

            </p>
            <i class="fas fa-angle-left right"></i>

          </a>

          <ul class="nav nav-treeview">

            <li class="nav-item">

              <a href="{{ route('user.create') }}" class="nav-link {{ (request()->routeIs('user.create')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Add User</p>

              </a>

            </li>

            <li class="nav-item">

              <a href="{{ route('user.index') }}" class="nav-link {{ (request()->routeIs('user.index')) ? 'active' : '' }}">

                <i class="fa fa-circle nav-icon"></i>

                <p>Manage User</p>

              </a>

            </li>

          </ul>

        </li>
        @endrole
      </ul>

    </nav>

    <!-- /.sidebar-menu -->

  </div>

  <!-- /.sidebar -->

</aside>