routes/web.php
<?php

use App\Http\Controllers\SaleController;

Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['auth']], function () {
	Route::get('/', 'Backend\BackendController@index')->name('home');	
});
		
Route::prefix('admin')->group(function () {
	Route::group(['middleware' => ['auth', 'role:admin']], function () {
		Route::resource('user', 'UserController');
	});
	
});

Route::resource('customer', 'CustomerController', ['names' => 'customer']);

Route::resource('product_category', 'ProductCategoryController', ['names' => 'product_category']);

Route::resource('product', 'ProductController', ['names' => 'product']);

Route::resource('sale', 'SaleController', ['names' => 'sale']);

Route::post('ajax/sub_category', 'AjaxController@sub_category')->name('ajax.sub_category');
Route::post('ajax/product_price', 'AjaxController@product_price')->name('ajax.product_price');
Route::post('ajax/customer_by_location', 'AjaxController@customer_by_location')->name('ajax.customer_by_location');


Route::get('customer_by_location', 'CustomerLocationcontroller@index')->name('customer_by_location.index');

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use DB;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{
	public function index()
	{
		// $role = Role::create(['name' => 'customer']);
		// $user = Auth::user();
		// $user->assignRole('admin');
		return view('backend.index');
	}

	
}

app/Http/Controllers/ProductCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Model\ProductCategory;
use Illuminate\Http\Request;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $productCategory = ProductCategory::asc()->get();
        return view('backend.productCategory.index', compact('productCategory'));
    }

    public function create()
    {
        return view('backend.productCategory.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'order' => 'nullable|integer|max:100',
        ]);

        $input = $request->all();
        if( empty($input['order']) ){
            $order = ProductCategory::max('order');
            $input['order'] = $order + 1;
        }
        ProductCategory::create($input);
        return redirect()->back()->with('success_msg', 'New Category Added Successfully.');
    }

   
    public function show(ProductCategory $productCategory)
    {
        //
    }

    public function edit(ProductCategory $productCategory)
    {
        return view('backend.productCategory.edit', compact('productCategory'));
    }

    public function update(Request $request, ProductCategory $productCategory)
    {
        $this->validate($request, [
            'name' => 'required',
            'order' => 'nullable|integer|max:100',
        ]);

        $input = $request->all();
        if( empty($input['order']) ){
            $order = ProductCategory::max('order');
            $input['order'] = $order + 1;
        }
        $productCategory->update($input);
        return redirect()->back()->with('success_msg', 'Category Updated Successfully.');
    }

    
    public function destroy(ProductCategory $productCategory)
    {
        $productCategory->delete();
        return redirect()->back()->with('success_msg', 'Category Deleted Successfully');
    }
}

resources/views/backend/productCategory/create.blade.php
@extends('backend.layouts.master')
@section('title')
Add New Category
@endsection

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                @include('flashMessage.message')
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <form action="{{ route('product_category.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-9">
                    <div class="card card-primary card-tabs">
                        <div class="card-header">
                            <h3 class="card-title">Category</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Category Name</label>
                                <input type="text" id="name" class="form-control" name="name"
                                    value="{{ old('name')?old('name'):'' }}">
                                @if($errors->has('name'))
                                <span class="text-danger">
                                    {{ $errors->first('name') }}
                                </span>
                                @endif
                            </div>
                                                      
                            <div class="form-group">
                                <label for="order">Order</label>
                                <input type="text" id="order" class="form-control"
                                    name="order"
                                    value="{{ old('order')?old('order'):'' }}">
                                    <span class="text-muted">
                                        Leaving this field empty will automatically set order to last category.
                                    </span>
                                @if($errors->has('order'))
                                <span class="text-danger">
                                    {{ $errors->first('order') }}
                                </span>
                                @endif
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>

                <div class="col-md-3">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Action</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Submit">
                                <a href="{{ route('product_category.index') }}" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection

resources/views/backend/productCategory/edit.blade.php
@extends('backend.layouts.master')
@section('title')
Category Edit
@endsection

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                @include('flashMessage.message')
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <form action="{{ route('product_category.update', $productCategory->id) }}" method="post">
            @csrf
            @method('put')
            <div class="row">
                <div class="col-md-9">
                    <div class="card card-primary card-tabs">
                        <div class="card-header">
                            <h3 class="card-title">Category</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Category Name</label>
                                <input type="text" id="name" class="form-control" name="name"
                                    value="{{ old('name')?old('name'):$productCategory->name }}">
                                @if($errors->has('name'))
                                <span class="text-danger">
                                    {{ $errors->first('name') }}
                                </span>
                                @endif
                            </div>
                                                      
                            <div class="form-group">
                                <label for="order">Order</label>
                                <input type="text" id="order" class="form-control"
                                    name="order"
                                    value="{{ old('order')?old('order'):$productCategory->order }}">
                                    <span class="text-muted">
                                        Leaving this field empty will automatically set order to last category.
                                    </span>
                                @if($errors->has('order'))
                                <span class="text-danger">
                                    {{ $errors->first('order') }}
                                </span>
                                @endif
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>

                <div class="col-md-3">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Action</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Submit">
                                <a href="{{ route('product_category.index') }}" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection

resources/views/backend/productCategory/index.blade.php
@extends('backend.layouts.master')

@section('title')
Manage Category
@endsection
@section('content')
<section class="content">
    @include('flashMessage.message')
    <div class="card">
        <div class="card-header">
            Categories
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">S.N</th>
                        <th scope="col">Category</th>
                        <th scope="col">Order</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($productCategory as $value)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$value->name}}</td>
                        <td>{{$value->order}}</td>
                        <td>
                            <form class="form-inline" method="post"
                                action="{{ route('product_category.destroy', $value->id) }}">
                                @csrf
                                @method('delete')
                                <a href="{{ route('product_category.edit', $value->id) }}" class="btn btn-primary m-2 btn-sm"><i
                                        class="fa fa-edit"> </i></a>
                                        <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm">                                                                                
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="5">
                            No data found!
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</section>
@stop