routes/web.php
<?php

use App\Http\Controllers\SaleController;

Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['auth']], function () {
	Route::get('/', 'Backend\BackendController@index')->name('home');	
});
		
Route::prefix('admin')->group(function () {
	Route::group(['middleware' => ['auth', 'role:admin']], function () {
		Route::resource('user', 'UserController');
	});
	
});

Route::resource('customer', 'CustomerController', ['names' => 'customer']);

Route::resource('product_category', 'ProductCategoryController', ['names' => 'product_category']);

Route::resource('product', 'ProductController', ['names' => 'product']);

Route::resource('sale', 'SaleController', ['names' => 'sale']);

Route::post('ajax/sub_category', 'AjaxController@sub_category')->name('ajax.sub_category');
Route::post('ajax/product_price', 'AjaxController@product_price')->name('ajax.product_price');
Route::post('ajax/customer_by_location', 'AjaxController@customer_by_location')->name('ajax.customer_by_location');


Route::get('customer_by_location', 'CustomerLocationcontroller@index')->name('customer_by_location.index');

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use DB;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{
	public function index()
	{
		// $role = Role::create(['name' => 'customer']);
		// $user = Auth::user();
		// $user->assignRole('admin');
		return view('backend.index');
	}

	
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Model\Product;
use App\Model\ProductCategory;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        if($request->ajax())
        {
            
            $data = Product::with('product_category')->latest()->get();

            return Datatables::of($data)
                    ->addColumn('action', function($data){
                        $button = '<a  class="btn btn-primary btn-sm" href="'.route('product.edit', $data->id).'"><i class="fa fa-edit"></i></a>';
                        $button .= '<button class="btn btn-danger btn-sm mx-1" id="'.$data->id.'" data-toggle="modal"
                        data-target="#deletePackageModal" onclick="deleteData('.$data->id.')"><i class="fa fa-trash"></i></button>';                
                        return $button;                
                    })
                    ->editColumn('category', function($data){
                        return $data->product_category->name;
                    })                    
                    ->editColumn('created_at', function($data){
                        return date('Y-m-d', strtotime($data->created_at) );
                    })
                    ->rawColumns(['action'])
                    ->addIndexColumn()
                    ->make(true);
        }

        return view('backend.product.index');
    }

    public function create()
    {
        $product_categories = ProductCategory::asc()->get();
        return view('backend.product.create', compact('product_categories'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|string|max:191',
            'price' => 'required|integer',
            'product_category_id' => 'required|integer'
        ]);

        Product::create($request->all());
        return redirect()->back()->with('success_msg', 'Product Added Successfully.');
    }

    public function show(Product $product)
    {
        //
    }

    public function edit(Product $product)
    {
        $product_categories = ProductCategory::asc()->get();
        return view('backend.product.edit', compact('product', 'product_categories'));
    }

    public function update(Request $request, Product $product)
    {
        $this->validate($request,[
            'name' => 'required|string|max:191',
            'price' => 'required|integer',
            'product_category_id' => 'required|integer'
        ]);

        $product->update($request->all());
        return redirect()->back()->with('success_msg', 'Product Updated Successfully.');
    }

    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->back()->with('success_msg', 'Product Deleted Successfully.');
    }
}

resources/views/backend/product/create.blade.php
@extends('backend.layouts.master')
@section('title')
Add New Product
@endsection

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                @include('flashMessage.message')
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <form action="{{ route('product.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-9">
                    <div class="card card-primary card-tabs">
                        <div class="card-header">
                            <h3 class="card-title">Product</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Product Name</label>
                                <input type="text" id="name" class="form-control" name="name"
                                    value="{{ old('name')?old('name'):'' }}">
                                @if($errors->has('name'))
                                <span class="text-danger">
                                    {{ $errors->first('name') }}
                                </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="price">Product Price (Rs)</label>
                                <input type="text" id="price" class="form-control" name="price"
                                    value="{{ old('price')?old('price'):'' }}">
                                @if($errors->has('price'))
                                <span class="text-danger">
                                    {{ $errors->first('price') }}
                                </span>
                                @endif
                            </div>
                                                      
                            <div class="form-group">
                                <div class="input-group-prepend">
                                    <label for="product_category_id">Category</label>
                                </div>
                                <select class="custom-select" id="product_category_id" name="product_category_id">
                                    <option>Choose product categories below...</option>
                                    @foreach ($product_categories as $item)
                                    <option value="{{ $item->id }}" {{ (old('product_category_id') == $item->id)?'selected':'' }}>{{ ucfirst($item->name) }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('product_category_id'))
                                <span class="text-danger">
                                    Please select the category.
                                </span>
                                @endif
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>

                <div class="col-md-3">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Action</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Submit">
                                <a href="{{ route('product.index') }}" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection

resources/views/backend/product/edit.blade.php
@extends('backend.layouts.master')
@section('title')
Product Edit
@endsection

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                @include('flashMessage.message')
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <form action="{{ route('product.update', $product->id) }}" method="post">
            @csrf
            @method('put')
            <div class="row">
                <div class="col-md-9">
                    <div class="card card-primary card-tabs">
                        <div class="card-header">
                            <h3 class="card-title">Product</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Product Name</label>
                                <input type="text" id="name" class="form-control" name="name"
                                    value="{{ old('name')?old('name'):$product->name }}">
                                @if($errors->has('name'))
                                <span class="text-danger">
                                    {{ $errors->first('name') }}
                                </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="price">Product Price (Rs)</label>
                                <input type="text" id="price" class="form-control" name="price"
                                    value="{{ old('price')?old('price'):$product->price }}">
                                @if($errors->has('price'))
                                <span class="text-danger">
                                    {{ $errors->first('price') }}
                                </span>
                                @endif
                            </div>
                                                      
                            <div class="form-group">
                                <div class="input-group-prepend">
                                    <label for="product_category_id">Category</label>
                                </div>
                                <select class="custom-select" id="product_category_id" name="product_category_id">
                                    <option>Choose product categories below...</option>
                                    @foreach ($product_categories as $item)
                                    <option value="{{ $item->id }}" {{ (($item->id==$product->product_category_id)?'selected':'') }}>
                                        {{ ucfirst($item->name) }} 
                                    </option>
                                    @endforeach
                                </select>
                                @if($errors->has('product_category_id'))
                                <span class="text-danger">
                                    Please select the category.
                                </span>
                                @endif
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>

                <div class="col-md-3">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Action</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Submit">
                                <a href="{{ route('product.index') }}" class="btn btn-danger">Close</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection

resources/views/backend/product/index.blade.php
@extends('backend.layouts.master')
@section('title')
Product
@endsection

@section('custom_css')
<link href="{{ asset('dataTable/css/jquery.dataTables.min.css') }}" rel="stylesheet">
{{-- <link href="{{ asset('dataTable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet"> --}}
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Customers</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="packages_table" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th width="5%">
                                        S.N
                                    </th>
                                    <th width="20%">
                                        Name
                                    </th>
                                    <th width="20%">
                                        Category
                                    </th>
                                    <th width="15%">
                                        Price
                                    </th>
                                    <th width="20%">
                                        Created At
                                    </th>
                                    <th width="20% ">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->

    <div class="modal" id="deletePackageModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="" method="post" id="deleteForm">
                    <div class="modal-header">
                        <h4 class="modal-title">Delete Customer</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @csrf
                        @method('delete')
                        Are you sure you want to delete this customer?
                    </div>
                    <div class=" modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger" data-dismiss="modal"
                            onclick="formSubmit()">Yes</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@endsection

@section('script')
<script src="{{ asset('jQuery/jquery-3.3.1.js') }}"></script>
<script src="{{ asset('dataTable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('dataTable/js/dataTables.bootstrap4.min.js') }}"></script>

<script>
    $(document).ready( function () {
        $('#packages_table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('product.index') }}",
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex' },
                { data: 'name', name: 'name' },
                { data: 'category', name: 'category' },
                { data: 'price', name: 'price' },
                { data: 'created_at', name: 'created_at' },
                { data: 'action', name: 'action', orderable:false },
            ]
        });
    });  

    function deleteData(id)
    {
        var id = id;
        var url = '{{ route("product.destroy", ":id") }}';
        url = url.replace(':id', id);
        $("#deleteForm").attr('action', url);
    }

    function formSubmit()
    {
        $("#deleteForm").submit();
    }     
</script>
@endsection