routes/web.php
<?php

use App\Http\Controllers\SaleController;

Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['auth']], function () {
	Route::get('/', 'Backend\BackendController@index')->name('home');	
});
		
Route::prefix('admin')->group(function () {
	Route::group(['middleware' => ['auth', 'role:admin']], function () {
		Route::resource('user', 'UserController');
	});
	
});

Route::resource('customer', 'CustomerController', ['names' => 'customer']);

Route::resource('product_category', 'ProductCategoryController', ['names' => 'product_category']);

Route::resource('product', 'ProductController', ['names' => 'product']);

Route::resource('sale', 'SaleController', ['names' => 'sale']);

Route::post('ajax/sub_category', 'AjaxController@sub_category')->name('ajax.sub_category');
Route::post('ajax/product_price', 'AjaxController@product_price')->name('ajax.product_price');
Route::post('ajax/customer_by_location', 'AjaxController@customer_by_location')->name('ajax.customer_by_location');


Route::get('customer_by_location', 'CustomerLocationcontroller@index')->name('customer_by_location.index');

app/User.php
<?php

namespace App;

use App\Model\Sale;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasRoles;

    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'referral_id', 'address', 'dob', 'phone_number'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];    

    public function sales()
    {
        return $this->hasMany(Sale::class);
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use DB;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{
	public function index()
	{
		// $role = Role::create(['name' => 'customer']);
		// $user = Auth::user();
		// $user->assignRole('admin');
		return view('backend.index');
	}

	
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Support\Facades\Hash;
use DB;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
	{		
		$auth_users = auth()->user();
		if(  $auth_users->hasAnyRole(['admin', 'editor'])  ){
			
			$users = User::with('roles')
			->latest()
			->get();

		}
		
		// dd($user);
		return view('backend.user.index', compact('users'));
	}

	public function create()
	{
		$roles = Role::all();
		// dd($roles);
		return view('backend.user.create', compact('roles'));
	}

	public function store(Request $request)
	{
		$this->validate($request, [
			'name' => 'required',
			'email' => 'required|email|unique:users,email',
			'password' => 'required|min:6|confirmed',
			'user_role' => 'required',
			]);    
			
		// dd($request->all());

		$user_id = Auth::user()->id;
		$input = $request->all();
		$input['password'] = Hash::make($input['password']);
		$input['referral_id'] = $user_id;
        $user = User::create($input);
		
		$user->assignRole($input['user_role']);
		return redirect()->back()->with('success_msg', 'User Created Successfully.');
	}

	public function edit($id)
	{
		$user = User::findOrFail($id);
		$roles = Role::all();
		$user_role_array = $user->getRoleNames()->toArray();		
		// dd($user_role_array);
		return view('backend.user.edit', compact('user', 'roles', 'user_role_array'));
	}

	public function update(Request $request, $id)
	{
		$this->validate($request, [
			'name' => 'required|string',
			'email' => 'required|unique:users,email,'.$id,
			'user_role' => 'required',
			]);    
			
		// dd($request->all());
		$input = $request->all();
		if(!empty($request['password'])){
			$input['password'] = Hash::make($request->password);
		}else{
			unset($input['password']);
		}
		$user = User::findOrFail($id);
		$user->update($input);
		DB::table('model_has_roles')->where('model_id',$id)->delete();
		$user->assignRole($request->user_role);
		return redirect()->back()->with('success_msg', 'User Updated Successfully.');
	}

	public function destroy($id)
	{
		$user = User::findOrFail($id);
		$user->delete();
		return redirect()->back()->with('success_msg', 'User Updated Successfully.');
	}
}

resources/views/backend/user/create.blade.php
@extends('backend.layouts.master')
@section('title')
User Add
@endsection

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                @include('flashMessage.message')
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <form action="{{ route('user.store') }}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-9">
                    <div class="card card-primary card-tabs">
                        <div class="card-header">
                            <h3 class="card-title">Users</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">User Name</label>
                                <input type="text" id="name" class="form-control" name="name"
                                    value="{{ old('name')?old('name'):'' }}" required>
                                @if($errors->has('name'))
                                <span class="text-danger">
                                    {{ $errors->first('name') }}
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" id="email" class="form-control" name="email"
                                    value="{{ old('email')?old('email'):'' }}" required>
                                @if($errors->has('email'))
                                <span class="text-danger">
                                    {{ $errors->first('email') }}
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="phone_number">Phone Number</label>
                                <input type="text" id="phone_number" class="form-control" name="phone_number"
                                    value="{{ old('phone_number')?old('phone_number'):'' }}" required>
                            </div>
                            <div class="form-group">
                                <label for="address">Address</label>
                                <input type="text" id="address" class="form-control" name="address"
                                    value="{{ old('address')?old('address'):'' }}" required>                                
                            </div>
                            <div class="form-group">
                                <label for="dob">Date of birth</label>
                                <input type="date" id="dob" class="form-control" name="dob"
                                    value="{{ old('dob')?old('dob'):'' }}" required>                                
                            </div>

                            <div class="form-group">
                                <div class="input-group-prepend">
                                    <label for="user_role">Role</label>
                                </div>
                                <select class="custom-select" id="user_role" name="user_role">
                                    {{-- <option>Choose</option> --}}
                                    @foreach ($roles as $item)
                                    <option value="{{ $item->name }}">{{ ucfirst($item->name) }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('user_role'))
                                <span class="text-danger">
                                    {{ $errors->first('user_role') }}
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="password">
                                    password
                                </label>
                                <input type="password" id="password" class="form-control" name="password"
                                    value="{{ old('password')?old('password'):'' }}" required>
                                <small class="text-muted">6 character required.</small>
                                @if($errors->has('password'))
                                <span class="text-danger">
                                    {{ $errors->first('password') }}
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="password_confirmation">Confirm Password</label>
                                <input type="password" id="password_confirmation" class="form-control"
                                    name="password_confirmation"
                                    value="{{ old('password_confirmation')?old('password_confirmation'):'' }}">
                                @if($errors->has('password_confirmation'))
                                <span class="text-danger">
                                    {{ $errors->first('password_confirmation') }}
                                </span>
                                @endif
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>

                <div class="col-md-3">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Action</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Publish">
                                <a href="{{ route('user.index') }}" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection

@section('script')
<script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>

<script>
    CKEDITOR.replace( 'description' );
</script>
@endsection

resources/views/backend/user/edit.blade.php
@extends('backend.layouts.master')
@section('title')
User Edit
@endsection

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12">
                @include('flashMessage.message')
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <form action="{{ route('user.update', $user->id) }}" method="post">
            @csrf
            @method('put')
            <div class="row">
                <div class="col-md-9">
                    <div class="card card-primary card-tabs">
                        <div class="card-header">
                            <h3 class="card-title">Users</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">User Name</label>
                                <input type="text" id="name" class="form-control" name="name"
                                    value="{{ old('name')?old('name'):$user->name }}" required>
                                @if($errors->has('name'))
                                <span class="text-danger">
                                    {{ $errors->first('name') }}
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="email">email</label>
                                <input type="email" id="email" class="form-control" name="email"
                                    value="{{ old('email')?old('email'):$user->email }}" required>
                                @if($errors->has('email'))
                                <span class="text-danger">
                                    {{ $errors->first('email') }}
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="phone_number">Phone Number</label>
                                <input type="text" id="phone_number" class="form-control" name="phone_number"
                                    value="{{ old('phone_number')?old('phone_number'):$user->phone_number }}" required>
                            </div>
                            <div class="form-group">
                                <label for="address">Address</label>
                                <input type="text" id="address" class="form-control" name="address"
                                    value="{{ old('address')?old('address'):$user->address }}" required>                                
                            </div>
                            <div class="form-group">
                                <label for="dob">Date of birth</label>
                                <input type="date" id="dob" class="form-control" name="dob"
                                    value="{{ old('dob')?old('dob'):$user->dob }}" required>                                
                            </div>
                            <div class="form-group">
                                <div class="input-group-prepend">
                                    <label for="user_role">Role</label>
                                </div>
                                <select class="custom-select" id="user_role" name="user_role">
                                    {{-- <option>Choose</option> --}}
                                    @foreach ($roles as $item)
                                    <option value="{{ $item->name }}"
                                        {{ (in_array($item->name, $user_role_array))?'selected':'' }}>
                                        {{ ucfirst($item->name) }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('user_role'))
                                <span class="text-danger">
                                    {{ $errors->first('user_role') }}
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="password">
                                    password
                                </label>
                                <input type="password" id="password" class="form-control" name="password"
                                    value="{{ old('password')?old('password'):'' }}">
                                <small class="text-red">Type password only if you want to change it!</small>
                                @if($errors->has('password'))
                                <span class="text-danger">
                                    {{ $errors->first('password') }}
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="password_confirmation">Confirm Password</label>
                                <input type="password" id="password_confirmation" class="form-control"
                                    name="password_confirmation"
                                    value="{{ old('password_confirmation')?old('password_confirmation'):'' }}">
                                @if($errors->has('password_confirmation'))
                                <span class="text-danger">
                                    {{ $errors->first('password_confirmation') }}
                                </span>
                                @endif
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>

                <div class="col-md-3">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Action</h3>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Publish">
                                <a href="{{ route('backend.user_index') }}" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
@endsection

@section('script')
<script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>

<script>
    CKEDITOR.replace( 'description' );
</script>
@endsection

resources/views/backend/user/index.blade.php
@extends('backend.layouts.master')

@section('title')
Manage User
@endsection
@section('content')
<section class="content">
    @include('flashMessage.message')
    <div class="card">
        <div class="card-header">
            Users
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">S.N</th>
                        <th scope="col">User</th>
                        <th scope="col">Email</th>
                        <th scope="col">Role</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($users as $value)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$value->name}}</td>
                        <td>{{$value->email}}</td>
                        <td>
                            <label class="badge badge-success">{{ $value->getRoleNames() }}</label>
                        </td>
                        <td>
                            <form class="form-inline" method="post"
                                action="{{ route('user.destroy', $value->id) }}">
                                @csrf
                                @method('delete')
                                <a href="{{ route('user.edit', $value->id) }}" class="btn btn-primary m-2 btn-sm"><i
                                        class="fa fa-edit"> </i></a>
                                    @if (Auth::user()->id != $value->id)
                                        <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm">                                        
                                        @else
                                        <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-danger btn-sm" disabled>                                                                                
                                    @endif
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="5">
                            No data found!
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</section>
@stop